In [8]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("aravind3505/dengue-detection-dataset-clinical-data")

print("Path to dataset files:", path)

Path to dataset files: /home/codespace/.cache/kagglehub/datasets/aravind3505/dengue-detection-dataset-clinical-data/versions/1

In [15]:
dic = pd.read_csv("/home/codespace/.cache/kagglehub/datasets/aravind3505/dengue-detection-dataset-clinical-data/versions/1/data_dictionary.csv")

dic.head()

          Column Name                                     Description
0                 age                     Age of the patient in years
1              gender             Gender of the patient (Male/Female)
2     hemoglobin_g_dl  Hemoglobin level in grams per deciliter (g/dL)
3           wbc_count   White blood cell count (cells per microliter)
4  differential_count             Differential white blood cell count

In [ ]:
import pandas as pd
df = pd.read_csv("/home/codespace/.cache/kagglehub/datasets/aravind3505/dengue-detection-dataset-clinical-data/versions/1/Dengue_diseases_dataset_modified (1).csv")
df.head()

,age,gender,hemoglobin_g_dl,wbc_count,differential_count,rbc_count,platelet_count,platelet_distribution_width,dengue_label
0,43,Male,12.6,2200.0,1,1,62000.0,11.0,1
1,45,Male,13.2,3000.0,0,1,17000.0,17.0,1
2,50,Female,11.0,3300.0,1,1,19000.0,16.3,1
3,57,Female,11.9,3500.0,1,0,29000.0,14.0,1
4,51,Female,13.0,3100.0,0,1,30000.0,14.5,1